"""add hs_api columns to organizations

Revision ID: 101ec71d4920
Revises: e7f8a9b0c1d2
Create Date: 2026-02-27 14:29:59.273013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101ec71d4920'
down_revision = 'e7f8a9b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('business', sa.String(length=200), nullable=False),
    sa.Column('location_identifier', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_requests_email'), ['email'], unique=False)

    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_push_token_user_token')
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_token'), ['token'], unique=False)

    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_channels_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('dayparts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_dayparts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_unique_constraint('uq_daypart_org_name', ['organization_id', 'name'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_employees_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_locations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('free_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hs_api_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('hs_api_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hs_api_password', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_organizations_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_positions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_unique_constraint('uq_position_org_name', ['organization_id', 'name'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_schedules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_requests_created_at'))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_system_settings_organization_id'), ['organization_id'], unique=True)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('training_roadmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_training_roadmaps_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_training_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_push', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint('uq_user_org_email', ['organization_id', 'email'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_org_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('notify_push')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_training_sessions_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('training_roadmaps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_training_roadmaps_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_system_settings_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_requests_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_schedules_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_position_org_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_positions_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_stripe_customer_id'))
        batch_op.drop_column('hs_api_password')
        batch_op.drop_column('hs_api_username')
        batch_op.drop_column('hs_api_url')
        batch_op.drop_column('trial_plan')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('billing_plan')
        batch_op.drop_column('free_plan')
        batch_op.drop_column('stripe_subscription_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_locations_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('dayparts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_daypart_org_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_dayparts_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_channels_organization_id'))
        batch_op.drop_column('organization_id')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('has_seen_tutorial', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_token'))

    op.drop_table('push_tokens')
    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signup_requests_email'))

    op.drop_table('signup_requests')
    # ### end Alembic commands ###
