"""Add performance indexes

Revision ID: 394550b40508
Revises: 
Create Date: 2026-02-17 15:25:50.895984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394550b40508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_channel_timestamp', ['channel_id', 'timestamp'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_training_sessions_schedule_date', ['schedule_id', 'session_date'], unique=False)
        batch_op.create_index('ix_training_sessions_trainee_completed', ['trainee_employee_id', 'completed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_training_sessions_trainee_completed')
        batch_op.drop_index('ix_training_sessions_schedule_date')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_channel_timestamp')

    # ### end Alembic commands ###
