"""add_guest_trainer_support

Revision ID: 867c312ff48f
Revises: a1b2c3d4e5f6
Create Date: 2026-02-19 22:16:25.768659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867c312ff48f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_trainer_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_trainer_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_trainer_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_trainer_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('trainer_employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('trainer_employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_trainer_name')

    with op.batch_alter_table('guest_trainer_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_trainer_tokens_token'))

    op.drop_table('guest_trainer_tokens')
    # ### end Alembic commands ###
