"""add_last_nudged_at_to_training_sessions

Revision ID: e4edb5fb55ec
Revises: 867c312ff48f
Create Date: 2026-02-19 22:38:18.655518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4edb5fb55ec'
down_revision = '867c312ff48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_nudged_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_nudged_at')

    # ### end Alembic commands ###
